CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -70,6 +70,12 @@ jobs:
           echo "::error Current action output doesn't contain '6.2.1': $OUTPUT"
           exit 1
         fi
+        if [ "${{ contains(fromJSON(env.OUTPUT), '0.8') }}" == "false" ]; then
+          echo "Valid"
+        else
+          echo "::error Current action output contains excluded '0.8': $OUTPUT"
+          exit 1
+        fi
         if [ "${{ contains(fromJSON(env.OUTPUT), '6.2') }}" == "false" ]; then
           echo "Valid"
         else
